services:
  - type: web
    name: flames-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        sync: false
      - key: MONGO_URI
        sync: false
      - key: GROQ_API_KEY
        sync: false
